### ISSUE TITLE
UI: Halaal Eats & Musalla

### ISSUE THREAD

**Issue by wafaajaunnoo** [wafaajaunnoo/bismillah.mu#8]
Fix:

1. List display for both pages
2. Pagination CSS

**Comment by rachidamrani** [comment]
Hi ! Can you explain more what is exactly the issue that you want to fix. I'd like to contribute if you don't mind.

**Comment by rachidamrani** [comment]
Hi ! could you explain more what is exactly the issue that you want to fix. I'd like to contribute if you don't mind :)

**Comment by wafaajaunnoo** [comment]
Hi, thanks a lot for your interest! I just wanted to improve the look of the UI with CSS3 and make both pages responsive  (check issue #6), possibly transitioning to Tailwind later on. Let me know if you're still interested, I'll send over the specifics.

**Comment by rachidamrani** [comment]
Ok let's do it! just send me your specifications and i'll try to make the pages responsive.

**Comment by wafaajaunnoo** [comment]
I've sent you an invite on Figma so that you can access the files. Let me know if you have any questions! :)

**Comment by wafaajaunnoo** [comment]
@rachidamrani any updates?

**Comment by rachidamrani** [comment]
I wanted to push some changes, using a new branch, to your repo but I could not do that cause I do not have permissions.

**Comment by wafaajaunnoo** [comment]
[FIXED]#9
